import { z } from 'zod';
export declare const domainMiniAppConfigSchema: z.ZodEffects<z.ZodObject<{
    version: z.ZodUnion<[z.ZodLiteral<"0.0.0">, z.ZodLiteral<"0.0.1">, z.ZodLiteral<"1">, z.ZodLiteral<"next">]>;
    name: z.ZodString;
    iconUrl: z.ZodString;
    homeUrl: z.ZodString;
    /** deprecated, set ogImageUrl instead */
    imageUrl: z.ZodOptional<z.ZodString>;
    /** deprecated, will rely on fc:frame/fc:miniapp meta tag */
    buttonTitle: z.ZodOptional<z.ZodString>;
    splashImageUrl: z.ZodOptional<z.ZodString>;
    splashBackgroundColor: z.ZodOptional<z.ZodString>;
    webhookUrl: z.ZodOptional<z.ZodString>;
    /** see: https://github.com/farcasterxyz/miniapps/discussions/191 */
    subtitle: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
    description: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
    screenshotUrls: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    primaryCategory: z.ZodOptional<z.ZodEnum<["games", "social", "finance", "utility", "productivity", "health-fitness", "news-media", "music", "shopping", "education", "developer-tools", "entertainment", "art-creativity"]>>;
    tags: z.ZodOptional<z.ZodArray<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>, "many">>;
    heroImageUrl: z.ZodOptional<z.ZodString>;
    tagline: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
    ogTitle: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
    ogDescription: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
    ogImageUrl: z.ZodOptional<z.ZodString>;
    /** see: https://github.com/farcasterxyz/miniapps/discussions/204 */
    noindex: z.ZodOptional<z.ZodBoolean>;
    /** see https://github.com/farcasterxyz/miniapps/discussions/256 */
    requiredChains: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodEnum<["eip155:1", "eip155:8453", "eip155:42161", "eip155:421614", "eip155:84532", "eip155:666666666", "eip155:100", "eip155:10", "eip155:11155420", "eip155:137", "eip155:11155111", "eip155:7777777", "eip155:130", "eip155:10143", "eip155:42220", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"]>, "many">, ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[], ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[]>>;
    requiredCapabilities: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodEnum<["wallet.getEthereumProvider", "wallet.getSolanaProvider", "actions.ready", "actions.openUrl", "actions.close", "actions.setPrimaryButton", "actions.addMiniApp", "actions.signIn", "actions.viewCast", "actions.viewProfile", "actions.composeCast", "actions.viewToken", "actions.sendToken", "actions.swapToken", "haptics.impactOccurred", "haptics.notificationOccurred", "haptics.selectionChanged", "back"]>, "many">, ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[], ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[]>>;
    /** see https://github.com/farcasterxyz/miniapps/discussions/158 */
    /** Documentation will be added once this feature is finalized. */
    castShareUrl: z.ZodOptional<z.ZodString>;
    /** Canonical domain for the miniapp application */
    canonicalDomain: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>, string, string>>;
}, "strip", z.ZodTypeAny, {
    name: string;
    version: "1" | "next" | "0.0.0" | "0.0.1";
    iconUrl: string;
    homeUrl: string;
    splashImageUrl?: string | undefined;
    splashBackgroundColor?: string | undefined;
    imageUrl?: string | undefined;
    buttonTitle?: string | undefined;
    webhookUrl?: string | undefined;
    subtitle?: string | undefined;
    description?: string | undefined;
    screenshotUrls?: string[] | undefined;
    primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
    tags?: string[] | undefined;
    heroImageUrl?: string | undefined;
    tagline?: string | undefined;
    ogTitle?: string | undefined;
    ogDescription?: string | undefined;
    ogImageUrl?: string | undefined;
    noindex?: boolean | undefined;
    requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
    requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
    castShareUrl?: string | undefined;
    canonicalDomain?: string | undefined;
}, {
    name: string;
    version: "1" | "next" | "0.0.0" | "0.0.1";
    iconUrl: string;
    homeUrl: string;
    splashImageUrl?: string | undefined;
    splashBackgroundColor?: string | undefined;
    imageUrl?: string | undefined;
    buttonTitle?: string | undefined;
    webhookUrl?: string | undefined;
    subtitle?: string | undefined;
    description?: string | undefined;
    screenshotUrls?: string[] | undefined;
    primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
    tags?: string[] | undefined;
    heroImageUrl?: string | undefined;
    tagline?: string | undefined;
    ogTitle?: string | undefined;
    ogDescription?: string | undefined;
    ogImageUrl?: string | undefined;
    noindex?: boolean | undefined;
    requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
    requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
    castShareUrl?: string | undefined;
    canonicalDomain?: string | undefined;
}>, {
    name: string;
    version: "1" | "next" | "0.0.0" | "0.0.1";
    iconUrl: string;
    homeUrl: string;
    splashImageUrl?: string | undefined;
    splashBackgroundColor?: string | undefined;
    imageUrl?: string | undefined;
    buttonTitle?: string | undefined;
    webhookUrl?: string | undefined;
    subtitle?: string | undefined;
    description?: string | undefined;
    screenshotUrls?: string[] | undefined;
    primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
    tags?: string[] | undefined;
    heroImageUrl?: string | undefined;
    tagline?: string | undefined;
    ogTitle?: string | undefined;
    ogDescription?: string | undefined;
    ogImageUrl?: string | undefined;
    noindex?: boolean | undefined;
    requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
    requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
    castShareUrl?: string | undefined;
    canonicalDomain?: string | undefined;
}, {
    name: string;
    version: "1" | "next" | "0.0.0" | "0.0.1";
    iconUrl: string;
    homeUrl: string;
    splashImageUrl?: string | undefined;
    splashBackgroundColor?: string | undefined;
    imageUrl?: string | undefined;
    buttonTitle?: string | undefined;
    webhookUrl?: string | undefined;
    subtitle?: string | undefined;
    description?: string | undefined;
    screenshotUrls?: string[] | undefined;
    primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
    tags?: string[] | undefined;
    heroImageUrl?: string | undefined;
    tagline?: string | undefined;
    ogTitle?: string | undefined;
    ogDescription?: string | undefined;
    ogImageUrl?: string | undefined;
    noindex?: boolean | undefined;
    requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
    requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
    castShareUrl?: string | undefined;
    canonicalDomain?: string | undefined;
}>;
export declare const domainManifestSchema: z.ZodEffects<z.ZodObject<{
    accountAssociation: z.ZodObject<{
        header: z.ZodString;
        payload: z.ZodString;
        signature: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        header: string;
        payload: string;
        signature: string;
    }, {
        header: string;
        payload: string;
        signature: string;
    }>;
    miniapp: z.ZodOptional<z.ZodEffects<z.ZodObject<{
        version: z.ZodUnion<[z.ZodLiteral<"0.0.0">, z.ZodLiteral<"0.0.1">, z.ZodLiteral<"1">, z.ZodLiteral<"next">]>;
        name: z.ZodString;
        iconUrl: z.ZodString;
        homeUrl: z.ZodString;
        /** deprecated, set ogImageUrl instead */
        imageUrl: z.ZodOptional<z.ZodString>;
        /** deprecated, will rely on fc:frame/fc:miniapp meta tag */
        buttonTitle: z.ZodOptional<z.ZodString>;
        splashImageUrl: z.ZodOptional<z.ZodString>;
        splashBackgroundColor: z.ZodOptional<z.ZodString>;
        webhookUrl: z.ZodOptional<z.ZodString>;
        /** see: https://github.com/farcasterxyz/miniapps/discussions/191 */
        subtitle: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
        description: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
        screenshotUrls: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        primaryCategory: z.ZodOptional<z.ZodEnum<["games", "social", "finance", "utility", "productivity", "health-fitness", "news-media", "music", "shopping", "education", "developer-tools", "entertainment", "art-creativity"]>>;
        tags: z.ZodOptional<z.ZodArray<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>, "many">>;
        heroImageUrl: z.ZodOptional<z.ZodString>;
        tagline: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
        ogTitle: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
        ogDescription: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
        ogImageUrl: z.ZodOptional<z.ZodString>;
        /** see: https://github.com/farcasterxyz/miniapps/discussions/204 */
        noindex: z.ZodOptional<z.ZodBoolean>;
        /** see https://github.com/farcasterxyz/miniapps/discussions/256 */
        requiredChains: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodEnum<["eip155:1", "eip155:8453", "eip155:42161", "eip155:421614", "eip155:84532", "eip155:666666666", "eip155:100", "eip155:10", "eip155:11155420", "eip155:137", "eip155:11155111", "eip155:7777777", "eip155:130", "eip155:10143", "eip155:42220", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"]>, "many">, ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[], ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[]>>;
        requiredCapabilities: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodEnum<["wallet.getEthereumProvider", "wallet.getSolanaProvider", "actions.ready", "actions.openUrl", "actions.close", "actions.setPrimaryButton", "actions.addMiniApp", "actions.signIn", "actions.viewCast", "actions.viewProfile", "actions.composeCast", "actions.viewToken", "actions.sendToken", "actions.swapToken", "haptics.impactOccurred", "haptics.notificationOccurred", "haptics.selectionChanged", "back"]>, "many">, ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[], ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[]>>;
        /** see https://github.com/farcasterxyz/miniapps/discussions/158 */
        /** Documentation will be added once this feature is finalized. */
        castShareUrl: z.ZodOptional<z.ZodString>;
        /** Canonical domain for the miniapp application */
        canonicalDomain: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>, string, string>>;
    }, "strip", z.ZodTypeAny, {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    }, {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    }>, {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    }, {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    }>>;
    frame: z.ZodOptional<z.ZodEffects<z.ZodObject<{
        version: z.ZodUnion<[z.ZodLiteral<"0.0.0">, z.ZodLiteral<"0.0.1">, z.ZodLiteral<"1">, z.ZodLiteral<"next">]>;
        name: z.ZodString;
        iconUrl: z.ZodString;
        homeUrl: z.ZodString;
        /** deprecated, set ogImageUrl instead */
        imageUrl: z.ZodOptional<z.ZodString>;
        /** deprecated, will rely on fc:frame/fc:miniapp meta tag */
        buttonTitle: z.ZodOptional<z.ZodString>;
        splashImageUrl: z.ZodOptional<z.ZodString>;
        splashBackgroundColor: z.ZodOptional<z.ZodString>;
        webhookUrl: z.ZodOptional<z.ZodString>;
        /** see: https://github.com/farcasterxyz/miniapps/discussions/191 */
        subtitle: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
        description: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
        screenshotUrls: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        primaryCategory: z.ZodOptional<z.ZodEnum<["games", "social", "finance", "utility", "productivity", "health-fitness", "news-media", "music", "shopping", "education", "developer-tools", "entertainment", "art-creativity"]>>;
        tags: z.ZodOptional<z.ZodArray<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>, "many">>;
        heroImageUrl: z.ZodOptional<z.ZodString>;
        tagline: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
        ogTitle: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
        ogDescription: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>>;
        ogImageUrl: z.ZodOptional<z.ZodString>;
        /** see: https://github.com/farcasterxyz/miniapps/discussions/204 */
        noindex: z.ZodOptional<z.ZodBoolean>;
        /** see https://github.com/farcasterxyz/miniapps/discussions/256 */
        requiredChains: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodEnum<["eip155:1", "eip155:8453", "eip155:42161", "eip155:421614", "eip155:84532", "eip155:666666666", "eip155:100", "eip155:10", "eip155:11155420", "eip155:137", "eip155:11155111", "eip155:7777777", "eip155:130", "eip155:10143", "eip155:42220", "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"]>, "many">, ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[], ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[]>>;
        requiredCapabilities: z.ZodOptional<z.ZodEffects<z.ZodArray<z.ZodEnum<["wallet.getEthereumProvider", "wallet.getSolanaProvider", "actions.ready", "actions.openUrl", "actions.close", "actions.setPrimaryButton", "actions.addMiniApp", "actions.signIn", "actions.viewCast", "actions.viewProfile", "actions.composeCast", "actions.viewToken", "actions.sendToken", "actions.swapToken", "haptics.impactOccurred", "haptics.notificationOccurred", "haptics.selectionChanged", "back"]>, "many">, ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[], ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[]>>;
        /** see https://github.com/farcasterxyz/miniapps/discussions/158 */
        /** Documentation will be added once this feature is finalized. */
        castShareUrl: z.ZodOptional<z.ZodString>;
        /** Canonical domain for the miniapp application */
        canonicalDomain: z.ZodOptional<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>, string, string>>;
    }, "strip", z.ZodTypeAny, {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    }, {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    }>, {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    }, {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    }>>;
}, "strip", z.ZodTypeAny, {
    accountAssociation: {
        header: string;
        payload: string;
        signature: string;
    };
    miniapp?: {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    } | undefined;
    frame?: {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    } | undefined;
}, {
    accountAssociation: {
        header: string;
        payload: string;
        signature: string;
    };
    miniapp?: {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    } | undefined;
    frame?: {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    } | undefined;
}>, {
    accountAssociation: {
        header: string;
        payload: string;
        signature: string;
    };
    miniapp?: {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    } | undefined;
    frame?: {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    } | undefined;
}, {
    accountAssociation: {
        header: string;
        payload: string;
        signature: string;
    };
    miniapp?: {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    } | undefined;
    frame?: {
        name: string;
        version: "1" | "next" | "0.0.0" | "0.0.1";
        iconUrl: string;
        homeUrl: string;
        splashImageUrl?: string | undefined;
        splashBackgroundColor?: string | undefined;
        imageUrl?: string | undefined;
        buttonTitle?: string | undefined;
        webhookUrl?: string | undefined;
        subtitle?: string | undefined;
        description?: string | undefined;
        screenshotUrls?: string[] | undefined;
        primaryCategory?: "games" | "social" | "finance" | "utility" | "productivity" | "health-fitness" | "news-media" | "music" | "shopping" | "education" | "developer-tools" | "entertainment" | "art-creativity" | undefined;
        tags?: string[] | undefined;
        heroImageUrl?: string | undefined;
        tagline?: string | undefined;
        ogTitle?: string | undefined;
        ogDescription?: string | undefined;
        ogImageUrl?: string | undefined;
        noindex?: boolean | undefined;
        requiredChains?: ("eip155:1" | "eip155:8453" | "eip155:42161" | "eip155:421614" | "eip155:84532" | "eip155:666666666" | "eip155:100" | "eip155:10" | "eip155:11155420" | "eip155:137" | "eip155:11155111" | "eip155:7777777" | "eip155:130" | "eip155:10143" | "eip155:42220" | "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp")[] | undefined;
        requiredCapabilities?: ("wallet.getEthereumProvider" | "wallet.getSolanaProvider" | "actions.ready" | "actions.openUrl" | "actions.close" | "actions.setPrimaryButton" | "actions.addMiniApp" | "actions.signIn" | "actions.viewCast" | "actions.viewProfile" | "actions.composeCast" | "actions.viewToken" | "actions.sendToken" | "actions.swapToken" | "haptics.impactOccurred" | "haptics.notificationOccurred" | "haptics.selectionChanged" | "back")[] | undefined;
        castShareUrl?: string | undefined;
        canonicalDomain?: string | undefined;
    } | undefined;
}>;
